In diesem Abschnitt schreibst du dein erstes eigenes Programm.
Du lernst wie du Daten, d.h. Text und Zahlen auf dem Bilschirm bekommst.

* [ ] Starte Programmierumgebung
* [ ] Klicke auf *Datei* und dann auf **Neu**
* [ ] Klicke auf *Datei* und dann *Speichern* und speichere die Datei unter dem Namen *Bildschirmausgabe* ab.

TIP: Notiere die beiden Funktionen, die schon eingetragen sind.

Antwort:

'''
'''

TIP: Was unterscheidet beide Funktionen? Welche kannst du löschen und das Programm funktioniert trotzdem?

Ändere dazu das Programm nach belieben und lade es auf den Mikrocontroller. Fülle dann folgende Tabelle aus:

.Mikrocontroller Funktionen
|===
|     | *die erste Mikrocontroller-Funktion*  |    *die zweite Mikrocontroller-Funktion* 
|Name |                       |
|Rückgabewert|                |
|Parameter
|
|
|Bedeutung
|
|
|wird so oft durchlaufen
|
|
|kann gelöscht werden
|
|
|===

## Ausgabe auf dem Bildschirm ##

Um Daten auf dem Bildschirm zu schreiben gibt es die Funktion println()
Ergänze die fehlenden Zeilen in der loop()-Funktion:

.app.rb
[source,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----

[source,CPP]
----
include::/Code/01_LEDblinken.ino[]
----

Um die Ausgabe vom Arduino auf dem Bildschirm anzeigen zu lassen. Muss du zuerst in der Funktion setup\(\) die Übertragungsrate festlegen.

```c
void setup() {
  Serial.begin(9600);
}
```

Öffne nun den "Monitor". **Hier Bild einfügen.**

* [ ] Schreibe dein Programm zu den Quadratzahlen.
* [ ] Teste dein Programm und kommentiere es.
* [ ] Nach Rücksprach mit dem Lehrer darfst du es ausdrucken und abheften. Geschafft! 💪 
