## Dein erstes Programm - Die Ampelschaltung ##

In diesem Abschnitt schreibst du dein erstes eigenes Programm.
Du lernst wie du eine externe LED ansteuern kannst.

Du brauchst dazu wieder die Schaltung mit der roten LED aus dem vorherigen Kapitel.

* [ ] Starte Programmierumgebung
* [ ] Klicke auf *Datei* und dann auf **Neu**
* [ ] Klicke auf *Datei* und dann *Speichern* und speichere die Datei unter dem Namen *Ampelsteuerung* ab.

TIP: Notiere die beiden Funktionen, die schon eingetragen sind.

Antwort:

'''
'''

TIP: Was unterscheidet beide Funktionen? Welche kannst du löschen und das Programm funktioniert trotzdem?

Ändere dazu das Programm nach belieben und lade es auf den Mikrocontroller. Fülle dann folgende Tabelle aus:

.Mikrocontroller Funktionen
|===
|     | *die erste Mikrocontroller-Funktion*  |    *die zweite Mikrocontroller-Funktion* 
|Name |                       |
|Rückgabewert|                |
|Parameter
|
|
|Bedeutung
|
|
|wird so oft durchlaufen
|
|
|kann gelöscht werden
|
|
|===

## Die Ampelschaltung ##

Schreibe das folgende Programm ab bzw. ergänze die fehlenden Code-Zeilen.

.01_blinken.ino
[source,cpp]
----
// global Variables
int LEDrot = D0;
int LEDgelb = D1;


// the setup function runs once when you press reset or power the board
void setup() {
  pinMode(LEDrot, OUTPUT); // initialize digital pin D1 as an output
  pinMode(LEDgelb, OUTPUT); // initialize digital pin D1 as an output
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LEDred, HIGH); // sets the pin D1 to HIGH voltage
  delay(1000);  // waits some time
  digitalWrite(LEDred, LOW);
  delay(1000); 
}
----

TIP: Ergänze dein Programm so, dass noch eine *grüne LED an Pin D2* angeschlossen werden kann. Baue dann die Schaltung mit der zusätzlichen grünen LED auf.

TIP: Schreibe dein Programm so um, dass eine *Ampelsteuerung" entsteht.
TIP: Speichere dein Programm.

Geschafft! 💪 
