In diesem Abschnitt schreibst du dein erstes eigenes Programm.
Du lernst wie du eine externe LED ansteuern kannst.

Baue dazu folgende Schaltung auf dem Steckbrett auf.
Bild 1 LED


* [ ] Starte Programmierumgebung
* [ ] Klicke auf *Datei* und dann auf **Neu**
* [ ] Klicke auf *Datei* und dann *Speichern* und speichere die Datei unter dem Namen *Bildschirmausgabe* ab.

TIP: Notiere die beiden Funktionen, die schon eingetragen sind.

Antwort:

'''
'''

TIP: Was unterscheidet beide Funktionen? Welche kannst du löschen und das Programm funktioniert trotzdem?

Ändere dazu das Programm nach belieben und lade es auf den Mikrocontroller. Fülle dann folgende Tabelle aus:

.Mikrocontroller Funktionen
|===
|     | *die erste Mikrocontroller-Funktion*  |    *die zweite Mikrocontroller-Funktion* 
|Name |                       |
|Rückgabewert|                |
|Parameter
|
|
|Bedeutung
|
|
|wird so oft durchlaufen
|
|
|kann gelöscht werden
|
|
|===

## Ausgabe auf dem Bildschirm ##

Ergänze die fehlenden Zeilen in der loop()-Funktion:

.01_blinken.ino
[source,cpp]
----
// global Variables
int LEDred = D2;


// the setup function runs once when you press reset or power the board
void setup() {
  pinMode(LEDred, OUTPUT); // initialize digital pin D2 as an output
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LEDred, HIGH); // sets the pin D2 to HIGH voltage
  delay(1000);  // waits some time
  digitalWrite(LEDred, LOW);
  delay(1000); 
}
----

Um die Ausgabe vom Arduino auf dem Bildschirm anzeigen zu lassen. Muss du zuerst in der Funktion setup\(\) die Übertragungsrate festlegen.

```c
void setup() {
  Serial.begin(9600);
}
```
Die Funktion um Daten auf dem Bildschirm zu schreiben heißt *println()*.

Öffne nun den "Monitor". **Hier Bild einfügen.**

* [ ] Schreibe dein Programm zu den Quadratzahlen.
* [ ] Teste dein Programm und kommentiere es.
* [ ] Nach Rücksprach mit dem Lehrer darfst du es ausdrucken und abheften. Geschafft! 💪 
